### ISSUE TITLE
Crashes on a function with no arguments

### ISSUE THREAD

**Issue by starius** [minio/c2goasm#15]
I am using 64 bit Linux, clang 6 and latest c2goasm (61af18eb2ccf8ddcf2a7157e864034c90e9ecc84) and asm2plan9s (90679c2ae83a1f72e371ea3476e862f619044d47).

```
$ cat f.c
int buz() {
    return 42;
}

$ clang-6.0 -O3 -mavx -mfma -masm=intel -fno-asynchronous-unwind-tables -fno-exceptions -fno-rtti -S -o f.s f.c

$ cat f.s
        .text
        .intel_syntax noprefix
        .file   "f.c"
        .globl  buz                     # -- Begin function buz
        .p2align        4, 0x90
        .type   buz,@function
buz:                                    # @buz
# %bb.0:
        mov     eax, 42
        ret
.Lfunc_end0:
        .size   buz, .Lfunc_end0-buz
                                        # -- End function

        .ident  "clang version 6.0.0-1~bpo9+1 (tags/RELEASE_600/final)"
        .section        ".note.GNU-stack","",@progbits

$ cat gofunc/f_amd64.go
package gofunc

//go:nosescape
func _buz() (result int)

$ c2goasm -a f.s gofunc/f_amd64.s
Processing f.s
panic: runtime error: index out of range

goroutine 1 [running]:
main.getGolangArgs(0xc0000bc308, 0x3, 0xc000071140, 0xf, 0x0, 0x60dea8, 0x0, 0x0, 0x60dea8, 0x0, ...)
        c2goasm/arguments.go:89 +0x78e
main.parseCompanionFile(0xc000072e00, 0x11, 0xc0000bc308, 0x3, 0x0, 0x0, 0x1, 0x5235e8, 0xc0000a3930, 0xc000068c00)
        c2goasm/arguments.go:67 +0xc9
main.process(0xc0000c8100, 0x10, 0x10, 0xc000072e00, 0x11, 0x0, 0x0, 0x0, 0x0, 0x0)
        c2goasm/c2goasm.go:86 +0x203
main.main()
        c2goasm/c2goasm.go:264 +0x37e
```

I debugged this a bit and found that `match` variable is `[]string{"func _buz() (result int)", "_buz", "", " (result int)"}`. The subsequent code attempts to parse `match[2]` which is an empty string.

The following patch fixes the issue:

```diff
diff --git a/arguments.go b/arguments.go
index ee466aa..ea310ea 100644
--- a/arguments.go
+++ b/arguments.go
@@ -85,8 +85,10 @@ func getGolangArgs(protoName, goline string) (isFunc bool, args, rets []string,
                if match[1] == "_"+protoName {

                        args, rets = []string{}, []string{}
-                       for _, arg := range strings.Split(match[2], ",") {
-                               args = append(args, strings.Fields(arg)[0])
+                       if match[2] != "" {
+                               for _, arg := range strings.Split(match[2], ",") {
+                                       args = append(args, strings.Fields(arg)[0])
+                               }
                        }

                        trailer := strings.TrimSpace(match[3])
```

**Comment by silbinarywolf** [comment]
I also hit this, so I've put up a PR with your fix.
